/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cloud_logic_custom": [
        {
            "name": "test",
            "endpoint": "https://7mc30e37c4.execute-api.ap-southeast-1.amazonaws.com/dev",
            "region": "ap-southeast-1"
        }
    ],
    "aws_cognito_identity_pool_id": "ap-southeast-1:1b665de5-692d-4050-bc59-6313cc6d0bfc",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_PJ3XTT9vy",
    "aws_user_pools_web_client_id": "1gbrvr2tlhoqi8vpph74frlvcb",
    "oauth": {}
};


export default awsmobile;
