/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cloud_logic_custom": [
        {
            "name": "upload2",
            "endpoint": "https://2i438ui4ql.execute-api.ap-northeast-1.amazonaws.com/devtokyo",
            "region": "ap-northeast-1"
        },
        {
            "name": "alert2",
            "endpoint": "https://iop579pd7f.execute-api.ap-northeast-1.amazonaws.com/devtokyo",
            "region": "ap-northeast-1"
        },
        {
            "name": "accept2",
            "endpoint": "https://uivs4mccob.execute-api.ap-northeast-1.amazonaws.com/devtokyo",
            "region": "ap-northeast-1"
        }
    ],
    "aws_cognito_identity_pool_id": "ap-northeast-1:12ed0bb0-2d32-4b90-9d82-9eaab94c1852",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_owRVrumkQ",
    "aws_user_pools_web_client_id": "jgsmsr7juug7rothsmif3tfd6",
    "oauth": {
        "domain": "robinlove8895e8d8-8895e8d8-devtokyo.auth.ap-northeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://master.d2uwbzpigdvc7j.amplifyapp.com/",
        "redirectSignOut": "https://master.d2uwbzpigdvc7j.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_dynamodb_all_tables_region": "ap-northeast-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "upload2Table-devtokyo",
            "region": "ap-northeast-1"
        },
        {
            "tableName": "alert2Table-devtokyo",
            "region": "ap-northeast-1"
        },
        {
            "tableName": "accept2Table-devtokyo",
            "region": "ap-northeast-1"
        }
    ],
    "aws_user_files_s3_bucket": "upload2-s3150527-devtokyo",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
